config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  devise_for :users




 resources :subjects

 resources :notes do 
 	resources :concepts 
 end

 root :to => "notes#index"


  get 'all_notes', to: 'notes#all_notes'
  get 'read_notes', to: 'notes#read_notes'
  get 'unread_notes', to: 'notes#unread_notes'
  get 'recent_notes', to: 'notes#recent_notes'

  resources :todolists


  get 'ages', to: 'ages#aptitudes'

  get 'train', to: 'train#aptitudes'

  get 'probability', to: 'probability#aptitudes'

  get 'pipes', to: 'pipes#aptitudes' 

  get 'geomentry', to: 'geomentry#aptitudes' 


  get 'algebra', to: 'algebra#aptitudes'


  get 'static_pages', to: 'static_pages#aptitudes'


  resources :aptitudes

  delete "delete_all", to: 'todolists#delete_all'


  resources :daywise_notes


  resources :relationships

  get 'followers', to: "relationships#followers"

  get 'find_users', to: "relationships#find_users"

  resources :current_updates




 resources :today_notes	
 resources :weekly_notes
 resources :monthly_notes
 resources :urls


 resources :networks


 

 resources :monthly_tasks
 resources :setgoals
 
 resources :mark_notes

 get 'read_today', to: 'today_notes#read_notes'
 get 'unread_today', to: 'today_notes#unread_notes'
 

end

app/models/aptitude.rb
class Aptitude < ApplicationRecord

	has_many :types
end

app/models/concept.rb
class Concept < ApplicationRecord
  belongs_to :note
end

app/models/monthly_task.rb
class MonthlyTask < ApplicationRecord
end

app/models/network.rb
class Network < ApplicationRecord

	belongs_to :user


	has_many  :notes
end

app/models/note.rb
class Note < ApplicationRecord
	mount_uploader :attachment, AttachmentUploader

	has_many :revise_notes
	has_many :concepts

	has_many :quotes

	belongs_to :subject

	belongs_to :user
     





 



	def weekly_notes

	 date = Date.today 
	 start_date = date.at_beginning_of_week 
     end_date  = date.at_end_of_week  
     dates  = start_date.upto(end_date).to_a
     weekly_notes = Note.where(date: dates).order('created_at DESC') 

	end

def date

 if params[:date].present?
      user_date = Date.parse(params[:date]) 
      notes = Note.all.where(date: user_date).order("created_at DESC")
 end
end

end

app/models/relationship.rb
class Relationship < ApplicationRecord

	belongs_to :follower, class_name: 'User'

	belongs_to  :followed, class_name: 'User'
end

app/models/revise_note.rb
class ReviseNote < ApplicationRecord
  belongs_to :note
end

app/models/subject.rb
class Subject < ApplicationRecord

	has_many :notes
    
    belongs_to :user


 
     

	validates :name, uniqueness: true 
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/todaytask.rb
class Todaytask < ApplicationRecord
end

app/models/todolist.rb
class Todolist < ApplicationRecord

	belongs_to :user


	validates :todoitem, :timesheet, :presence => true


	def todolists
      current_user.todolists.count

	end
end

app/models/topic.rb
class Topic < ApplicationRecord
end

app/models/type.rb
class Type < ApplicationRecord

	belongs_to :aptitude
end

app/models/upload.rb
class Upload < ApplicationRecord

end

app/models/url.rb
class Url < ApplicationRecord
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

   



 
   

  has_many  :subjects
  has_many  :notes

  has_many  :todolists

  has_many :follower_relationships, class_name: 'Relationship', foreign_key: :follower_id
  has_many :followed_relationships, class_name: 'Relationship', foreign_key: :followed_id


  has_many :followers, through: :followed_relationships, source: :follower

  has_many :followed, through: :follower_relationships, source: :followed



def self.add_public_uid

   User.update(public_uid: SecureRandom.urlsafe_base64(3))

end  

end

app/controllers/monthly_notes_controller.rb
class MonthlyNotesController < ApplicationController

	def index

	end


	def show
    date = params[:id]

    new_date = Date.parse(date)

    end_date = new_date.at_end_of_month()

    dates = new_date.upto(end_date).to_a
	
	@monthly_notes = Note.all.where(date: dates).order('created_at DESC')


	end


end

app/helpers/concepts_helper.rb
module ConceptsHelper
end

app/helpers/monthly_notes_helper.rb
module MonthlyNotesHelper
end

app/helpers/networks_helper.rb
module NetworksHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/monthly_notes/index.html.erb
<div style ="margin-left: 300px; margin-right: 300px; margin-top: 100px;">	
  
 <% month = Date.parse('01/01/2020') %>

 <%=  link_to "#{month.strftime("%b %d, %Y")}", monthly_note_path(month) %>

 
<div style="list-style-type: none"> 
<% (0..11).each do |loop| %>
 
 <% month = month.next_month %>

  <%= link_to "#{month.strftime("%b %d, %Y")}", monthly_note_path(month)%> 


 <% end %>

</div>
</div>

</li>

app/views/monthly_notes/show.html.erb
<% newdate = Date.parse(params[:id]) %>

<%= newdate.strftime("%b %d, %Y") %> -

<%= newdate.at_end_of_month.strftime("%b %d, %Y") %>	


<% date= Date.parse (params[:id]) %>

<% start_date = date.at_beginning_of_month %>

<% end_date = date.at_end_of_month %>

<div style="margin-left: 300px; margin-right: 300px; margin-top: 50px; line-height: 50px;">

<% dates= start_date.upto(end_date).to_a %>
<div class="box">

<p> Datewise </p>
<% dates.each do |date| %>

 <%= link_to "#{date.strftime("%b %d")}", daywise_note_path(date) %>

<% end %>

</div>




</div>

<div style ="margin-left: 300px; margin-right: 300px; margin-top: 50px;">	

  <% @monthly_notes.each do |note|  %>
    <div class="box">		
<p class="has-text-weight-bold"><%= note.topic_name %>  <%= note.created_at %></p><br> 
<%= sanitize note.notes %>
 </div>
 <% end %>

</div>