config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  devise_for :users




 resources :subjects

 resources :notes do 
 	resources :concepts 
 end

 root :to => "notes#index"


  get 'all_notes', to: 'notes#all_notes'
  get 'read_notes', to: 'notes#read_notes'
  get 'unread_notes', to: 'notes#unread_notes'
  get 'recent_notes', to: 'notes#recent_notes'

  resources :todolists


  get 'ages', to: 'ages#aptitudes'

  get 'train', to: 'train#aptitudes'

  get 'probability', to: 'probability#aptitudes'

  get 'pipes', to: 'pipes#aptitudes' 

  get 'geomentry', to: 'geomentry#aptitudes' 


  get 'algebra', to: 'algebra#aptitudes'


  get 'static_pages', to: 'static_pages#aptitudes'


  resources :aptitudes

  delete "delete_all", to: 'todolists#delete_all'


  resources :daywise_notes


  resources :relationships

  get 'followers', to: "relationships#followers"

  get 'find_users', to: "relationships#find_users"

  resources :current_updates




 resources :today_notes	
 resources :weekly_notes
 resources :monthly_notes
 resources :urls


 resources :networks


 

 resources :monthly_tasks
 resources :setgoals
 
 resources :mark_notes

 get 'read_today', to: 'today_notes#read_notes'
 get 'unread_today', to: 'today_notes#unread_notes'
 

end

app/models/aptitude.rb
class Aptitude < ApplicationRecord

	has_many :types
end

app/models/concept.rb
class Concept < ApplicationRecord
  belongs_to :note
end

app/models/monthly_task.rb
class MonthlyTask < ApplicationRecord
end

app/models/network.rb
class Network < ApplicationRecord

	belongs_to :user


	has_many  :notes
end

app/models/note.rb
class Note < ApplicationRecord
	mount_uploader :attachment, AttachmentUploader

	has_many :revise_notes
	has_many :concepts

	has_many :quotes

	belongs_to :subject

	belongs_to :user
     





 



	def weekly_notes

	 date = Date.today 
	 start_date = date.at_beginning_of_week 
     end_date  = date.at_end_of_week  
     dates  = start_date.upto(end_date).to_a
     weekly_notes = Note.where(date: dates).order('created_at DESC') 

	end

def date

 if params[:date].present?
      user_date = Date.parse(params[:date]) 
      notes = Note.all.where(date: user_date).order("created_at DESC")
 end
end

end

app/models/relationship.rb
class Relationship < ApplicationRecord

	belongs_to :follower, class_name: 'User'

	belongs_to  :followed, class_name: 'User'
end

app/models/revise_note.rb
class ReviseNote < ApplicationRecord
  belongs_to :note
end

app/models/subject.rb
class Subject < ApplicationRecord

	has_many :notes
    
    belongs_to :user


 
     

	validates :name, uniqueness: true 
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/todaytask.rb
class Todaytask < ApplicationRecord
end

app/models/todolist.rb
class Todolist < ApplicationRecord

	belongs_to :user


	validates :todoitem, :timesheet, :presence => true


	def todolists
      current_user.todolists.count

	end
end

app/models/topic.rb
class Topic < ApplicationRecord
end

app/models/type.rb
class Type < ApplicationRecord

	belongs_to :aptitude
end

app/models/upload.rb
class Upload < ApplicationRecord

end

app/models/url.rb
class Url < ApplicationRecord
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

   



 
   

  has_many  :subjects
  has_many  :notes

  has_many  :todolists

  has_many :follower_relationships, class_name: 'Relationship', foreign_key: :follower_id
  has_many :followed_relationships, class_name: 'Relationship', foreign_key: :followed_id


  has_many :followers, through: :followed_relationships, source: :follower

  has_many :followed, through: :follower_relationships, source: :followed



def self.add_public_uid

   User.update(public_uid: SecureRandom.urlsafe_base64(3))

end  

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController


  before_action :set_note, only: [:show, :edit, :update, :destroy]
	
	def index	
	  @notes = current_user.notes.all.order(created_at: :desc)
      @note = current_user.notes.new
      @subject = current_user.subjects.new
      @subjects  = current_user.subjects.all.map { |s| [s.name, s.id]}

      @allsubjects = current_user.subjects.all

      date = Date.today

      start_date = date.at_beginning_of_year

      end_date = date.at_end_of_year

      @dates = start_date.upto(end_date).to_a
  end

    
    def  create
      @note = current_user.notes.create(notes_params)
    end
    
    def show

    end

    def edit
        @subjects  = current_user.subjects.all.map { |s| [s.name, s.id]}
    end

    def update
        @note.update(notes_params)
        binding.pry
        	redirect_to notes_path(@note)
    end
    def destroy
    	 @note.destroy
    end

    def all_notes

      @notes = current_user.notes.all.paginate(page: params[:page],per_page: 10).order('id DESC')

    end

    def unread_notes
    end

    def recent_notes
      @recent_notes = current_user.notes.last(1)
    end 

    def revise_notes
         @note = current_user.notes.find(params[:id])
         @note.update(mark_read: false)
         binding.pry
         redirect_to today_notes_path
    end
   
    private

    def notes_params
      params.require(:note).permit(:topic_name, :notes_date, :notes, :subject_id).merge(date: Date.today, user_id: current_user)
    end

    def set_note
         @note = current_user.notes.find(params[:id])
    end

  
end

app/helpers/concepts_helper.rb
module ConceptsHelper
end

app/helpers/networks_helper.rb
module NetworksHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/setgoals_helper.rb
module SetgoalsHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/notes/_form.html.erb
<%= form_for @note, local: true, data: {remote: true} do |f| %>

<div class="field">
	<div class="control">
 <%= f.label :topic_name %>
 <%= f.text_field :topic_name, placeholder: "Enter the topic name" %> 
  </div>
</div>

<%= f.label :notes %> 


<div class="field">
		<div class="control">
<%= f.text_area :notes, class: 'text_area' , placeholder: "Add/copy the notes here", :rows => 15, :cols => 60, autofocus: true %> <br>

</div>
</div>

<%= f.submit "Create notes", class: "button is-info" %>


<% end %>

</div>	

app/views/notes/_notes.html.erb
<div class ="notes-delete-<%= note.id %>">
<div class="box" style=" box-color: blue;">
	<div class="tags has-addons">

<%  subject = Subject.find_by(id: note.subject_id) %>

<% if subject.present? %>



   <%= link_to "#{subject.name}", subject_path(note.subject_id), class: "tag is-medium is-link" %> 

   </div>
   <div class="tags has-addons"> 	
  <span class="tag is-success is-medium"> <%= note.topic_name %></span> 
     <span class="tag is-primary is-medium is-pulled-right"> <%= note.created_at.localtime.strftime("%A, %b %d,  %l:%M %p") %>


      </span>
</div>

 	
     
     <%= simple_format note.notes %> <br>

     <%= link_to "Add subtopic", note_path(note) %> <br>

    <%= link_to "Edit Notes", edit_note_path(note) %> <br>
     
    <%= link_to "Delete Notes", note_path(note), method: :delete,  data: {remote: true } %>  
     <% end %>  
   </div>





</div><br> 

app/views/notes/_subject.html.erb
<div id="subject" style="margin-left: 200px; margin-right: 150px; margin-top: 80px;">
<%= form_for @note, local: true, data: {remote: true} do |f| %>

<div class="field">
	<div class="control">
 <%= f.label :name %>
 <%= f.text_field :name, placeholder: "Enter the Subject name" %> 
  </div>
</div>



<%= f.submit "Create Subject", class: "button is-info" %>


<% end %>

</div>	

app/views/notes/all_notes.html.erb
 <%= link_to "Back Home",  notes_path, class: "button is-link", style: "margin-top: 120px; margin-left: 160px;" %>
<%= will_paginate @notes %>

<div style ="margin-left: 350px; margin-right: 350px; margin-top: 150px;" >



   <%= render partial: 'notes', collection: @notes, as: :note %>
</div>

</div>

app/views/notes/create.js.erb
$(".notes").prepend("<%= j render 'notes', note: @note  %>")



$(":input:not(input[type=submit])").val("");

app/views/notes/destroy.js.erb
$(".notes-delete-<%= @note.id %>").remove();

app/views/notes/edit.html.erb
<div id="subject" style="margin-left: 200px; margin-right: 150px; margin-top: 80px;">
<%= form_for [@note, ], local: true do |f| %>

<div class="field">
	<div class="control">
<%= f.label :topic_name %>
<%= f.text_field :topic_name %> <br>
</div>
</div>



<%= f.label :notes %> 

 <%= f.text_area :notes %>


<div class="field">
	<div class="control">
<%= f.select(:subject_id, options_for_select(@subjects), prompt: 'select one') %> <br>

</div>
</div>


<%= f.submit %>


<% end %>

</div>


<script>
var simplemde = new SimpleMDE();


</script>

app/views/notes/follower.html.erb
<%= form_tag daywise_notes_path, method: :get do %>
  <p>
    <%= date_field_tag :date, params[:date] %>
    <%= submit_tag "Search by Date", name: nil, class: "button is-info", style: "line-height: 15px;" %>
  </p>
<% end %>

</div>

<h1 class="title is-1" style="margin-left: 200px; color: purple"> NotesMaker </h1>
<p style="margin-left: 200px;">  <strong> Quickly </strong> add your <strong style="color: green">  Notes </strong>  </p>


<div id="subject" style="margin-left: 350px; margin-top: 0px;">
  <%= form_for @subject, local: true, data: {remote: true} do |f| %>

    <div class="field">
      <div class="control">
        <%= f.label :name %>
        <%= f.text_field :name, placeholder: "Enter the Subject name" %>
      </div>
    </div>

    <%= f.submit "Create Subject", class: "button is-info" %>


  <% end %>

<%= link_to "Find & Follow user", find_users_path, style: "margin-left: 650px; margin-top: 10px;", class: "tag  is- primary is-medium" %>
<%= link_to "Followers Notes", followers_path, style: "margin-left: 650px; margin-top: 5px;", class: "tag  is- primary is-medium" %>
<%= link_to "Followings", relationships_path, style: "margin-left: 650px; margin-top: 5px;", class: "tag  is- primary is-medium" %>

app/views/notes/index.html.erb
<div  style="margin-left: 150px; margin-top: 100px; line-height: 20px;">








  <div style="margin-top: -140px; margin-left: 15px;">
   <span class="tag is-medium is-success" style=" margin-top: -10px"> Subjects </span>  
 </div>
  <div style="margin-left: 30px; margin-top: 15px;">
  <% @allsubjects.each do |subject| %>
   <li><%= link_to "#{subject.name}", subject_path(subject.id) %>(<%= subject.notes.count %>)</li>  

   
   <% end %>

   
  </div>
  
</div>	

<div style="margin-left: 160px; list-style-type: none; margin-top: 60px;">

  <li> <%= link_to "Today Notes", today_notes_path, class: "tag is-link" %> </li>  

  <li>  <%= link_to "Recent Notes", recent_notes_path, class: "tag is-link", style: "margin-top: 5px;" %> </li> 
  
   <li> <%= link_to "ALL Notes", all_notes_path, class: "tag is-link", style: "margin-top: 5px;" %> </li>


  </div>




<div id="form" style="margin-left: 10px; margin-top: 50px">	


	
<%= form_for @note, local: true, data: {remote: true} do |f| %>

<div class="field">
	<div class="control">

<div style="width: 50%; margin-right: 50px;">
<%= f.label :subject %>
<%= f.select(:subject_id, options_for_select((@subjects)), :prompt => "select Subject")	%> <br>

</div>
</div>
</div>	

<%= f.label :notes %> 


<div class="field">
<%= f.hidden_field :notes %>
<div style="width: 700px; margin-top: 5px; ">	
<%= f.text_area :notes, placeholder: "Add/copy the notes here",  autofocus: true %> <br>
</div>

<%= f.submit "Create notes", class: "button is-info", style: "margin-top: -35px;" %>


<% end %>

</div>	





<div  class="notes" style ="margin-left: 30px; margin-right: 230px; margin-top: 40px;" >
  	

<% if @notes.count < 5 %>

  <% @notes = current_user.notes.all %> 
   <%= render partial: 'notes', collection: @notes, as: :note %>

<% else %>

   <% @notes = current_user.notes.last(3) %> 
    <%= render partial: 'notes', collection: @notes, as: :note %>

<% end %>    
  
</div>

</div>

</div>

</div>



<footer class="footer" style="margin-top: 50px;  background-color: #DDA0DD">

  <h1 class="title is-2"> NotesMaker </h1>
  <div class="content has-text-centered">
    <p>
       The notesmaker designed and made in chennai(india).
    </p>
  </div>
</footer>



<script>
var simplemde = new SimpleMDE();


</script>

app/views/notes/new.html.erb
<div id="form" style="margin-left: 250px; margin-right: 150px; margin-top: 100px;">
<%= form_for @note, local: true do |f| %>

<%= f.label :topic_name %>
<%= f.text_field :topic_name %> <br>

<%= f.label :notes %> 

 <%= f.text_area :notes,    as: :trix_editor, :rows => 20, :cols => 80, autofocus: true %>




<%= f.submit "Create notes" %>


<% end %>

</div>

app/views/notes/read_notes.html.erb
<div style="margin-top: 20px; margin-left: 50px;">
<% read_notes = Note.where(mark_read: true) %>
<ol>
<% read_notes.each do |note| %>
<li> <%= link_to "#{note.topic_name}", note_path(note) %> </li>
<% end %>
</ol>

</div>

app/views/notes/recent_notes.html.erb
 <%= link_to "Back Home",  notes_path, class: "button is-link", style: "margin-top: 120px; margin-left: 160px;" %>

<div style ="margin-left: 300px; margin-right: 300px; margin-top: 50px;" >
	<% notes = @recent_notes.reverse %>
   <% notes.each do |note| %>
	<div class="box">	
    <% if note.mark_read.present? %>
	    <p class="has-text-weight-bold"><%= note.topic_name %>  <span style="margin-left: 20px; color: purple" width: 10px;> &#10004 </span> </p>
	<% end %>
  	<%= note.created_at.strftime("%A, %b %d") %>   
  	<%= link_to "View notes", note_path(note) , class: "button is-primary is-pulled-right" %> 	
<%= sanitize note.notes %>
</div>
<% end %>
</div>

app/views/notes/show.html.erb
<div style="margin-left: 150px; list-style-type: none; margin-top: 50px;">

<p>  </p>

<p> Sub topics (<%= @note.concepts.count %>)</p>
<% @note.concepts.each do |concept| %>

<li> <%= link_to "#{concept.name}" %> </li>

<% end %>


<div style="margin-top: 10px; margin-left: 200px; margin-right: 300px;">

<div class="box">
<h1> Topic name:  <%= @note.topic_name %> <%= link_to 'Edit notes', edit_note_path(@note) %> </h1>  	
<%=  sanitize @note.notes %>


<h1> Created on:  <%= @note.created_at.strftime("%A, %d %b %Y %l:%M %p")%> </h1> 




<%= link_to 'Delete', note_path(@note) , data: { confirm: "Are u want to delete this notes???" } %>

</div>
</div>

 <p style='font-size:35px; margin-left: 220px;  color: blue;'>&#8627;</p>

<% if @note.concepts.present? %>

<% @note.concepts.each do |concept| %>
<div id= "<%= concept.id %>" style="margin-left: 250px; margin-right: 200px; line-height: 20px;">

	<h1> concept :  <%= concept.name %> </h1>

<div class="box">
  <%= concept.created_at.strftime("%A, %d %b %Y %l:%M %p")%>  <br>

<%= sanitize concept.desc %>
</div>

 <p style='font-size:35px; margin-left: -5px;  color: blue;'>&#8627;</p>
</div>
<% end %>
	
<% end %>


<div style="margin-left: 250px; margin-right: 250px; margin-top: 10px;">
<%= form_with( model: [@note, @note.concepts.build], local: true) do |f| %>

<%= f.label :Concepts %>
<%= f.text_field :name %> <br>

<%= f.label :Description %> 

<div class="field">
	<div class="control">
 <%= f.text_area :desc,  placeholder: "Add/copy the notes here", autofocus: true %>
</div>
</div>


<%= f.submit "Add concepts" %>


<% end %>

</div>

<script>
var simplemde = new SimpleMDE();


</script>

app/views/notes/unread_notes.html.erb
<div style="margin-top: 100px; margin-left: 150px;">

<% read_notes = Note.where(mark_read: false) %>
<ol>
<% read_notes.each do |note| %>

<li> <%= link_to "#{note.topic_name}", note_path(note) %> </li>
<% end %>
</ol>

</div>