config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  devise_for :users




 resources :subjects

 resources :notes do 
 	resources :concepts 
 end

 root :to => "notes#index"


  get 'all_notes', to: 'notes#all_notes'
  get 'read_notes', to: 'notes#read_notes'
  get 'unread_notes', to: 'notes#unread_notes'
  get 'recent_notes', to: 'notes#recent_notes'

  resources :todolists


  get 'ages', to: 'ages#aptitudes'

  get 'train', to: 'train#aptitudes'

  get 'probability', to: 'probability#aptitudes'

  get 'pipes', to: 'pipes#aptitudes' 

  get 'geomentry', to: 'geomentry#aptitudes' 


  get 'algebra', to: 'algebra#aptitudes'


  get 'static_pages', to: 'static_pages#aptitudes'


  resources :aptitudes

  delete "delete_all", to: 'todolists#delete_all'


  resources :daywise_notes


  resources :relationships

  get 'followers', to: "relationships#followers"

  get 'find_users', to: "relationships#find_users"

  resources :current_updates




 resources :today_notes	
 resources :weekly_notes
 resources :monthly_notes
 resources :urls


 resources :networks


 

 resources :monthly_tasks
 resources :setgoals
 
 resources :mark_notes

 get 'read_today', to: 'today_notes#read_notes'
 get 'unread_today', to: 'today_notes#unread_notes'
 

end

app/models/aptitude.rb
class Aptitude < ApplicationRecord

	has_many :types
end

app/models/concept.rb
class Concept < ApplicationRecord
  belongs_to :note
end

app/models/monthly_task.rb
class MonthlyTask < ApplicationRecord
end

app/models/network.rb
class Network < ApplicationRecord

	belongs_to :user


	has_many  :notes
end

app/models/note.rb
class Note < ApplicationRecord
	mount_uploader :attachment, AttachmentUploader

	has_many :revise_notes
	has_many :concepts

	has_many :quotes

	belongs_to :subject

	belongs_to :user
     





 



	def weekly_notes

	 date = Date.today 
	 start_date = date.at_beginning_of_week 
     end_date  = date.at_end_of_week  
     dates  = start_date.upto(end_date).to_a
     weekly_notes = Note.where(date: dates).order('created_at DESC') 

	end

def date

 if params[:date].present?
      user_date = Date.parse(params[:date]) 
      notes = Note.all.where(date: user_date).order("created_at DESC")
 end
end

end

app/models/relationship.rb
class Relationship < ApplicationRecord

	belongs_to :follower, class_name: 'User'

	belongs_to  :followed, class_name: 'User'
end

app/models/revise_note.rb
class ReviseNote < ApplicationRecord
  belongs_to :note
end

app/models/subject.rb
class Subject < ApplicationRecord

	has_many :notes
    
    belongs_to :user


 
     

	validates :name, uniqueness: true 
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/todaytask.rb
class Todaytask < ApplicationRecord
end

app/models/todolist.rb
class Todolist < ApplicationRecord

	belongs_to :user


	validates :todoitem, :timesheet, :presence => true


	def todolists
      current_user.todolists.count

	end
end

app/models/topic.rb
class Topic < ApplicationRecord
end

app/models/type.rb
class Type < ApplicationRecord

	belongs_to :aptitude
end

app/models/upload.rb
class Upload < ApplicationRecord

end

app/models/url.rb
class Url < ApplicationRecord
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

   



 
   

  has_many  :subjects
  has_many  :notes

  has_many  :todolists

  has_many :follower_relationships, class_name: 'Relationship', foreign_key: :follower_id
  has_many :followed_relationships, class_name: 'Relationship', foreign_key: :followed_id


  has_many :followers, through: :followed_relationships, source: :follower

  has_many :followed, through: :follower_relationships, source: :followed



def self.add_public_uid

   User.update(public_uid: SecureRandom.urlsafe_base64(3))

end  

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController


	def index

        @users = current_user.followers.where.not(id: current_user.id).uniq
	end


	def create
 
     @relationship = Relationship.create(follower_id:  params[:follower_id], followed_id: current_user.id)

     redirect_to relationships_path

	end


	def destroy
     
     @relationship = Relationship.find_by(follower_id: params[:id])

     @relationship.destroy

     redirect_to relationships_path

    end


    def followers
    
    @users = current_user.followers.uniq

    end

    def find_users
     
     @user = User.new
     @user = User.find_by(username: params[:username])   
  
    end







end

app/helpers/concepts_helper.rb
module ConceptsHelper
end

app/helpers/networks_helper.rb
module NetworksHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/relationships/find_users.html.erb
<div style="margin-left: 250px; margin-top: 80px;">

<%= form_tag find_users_path, method: :get do %>
  <p>
  <%= text_field_tag :username, params[:username] %>
  <%= submit_tag "Search by username", class: "button is-info", style: "line-height: 20px;" %>
  </p>

<% end %>  

</div>






<div class="box" style="margin-left: 200px; width: 400px; margin-top: 150px;">

<% if @user.present? %>
<%=  @user.email %>   <%= link_to 'Follow', relationships_path(follower_id: @user&.id), method: :post, class:'button is-link is-pulled-right' %>  <br>
<%= link_to 'Unfollow', relationship_path(@user.id), method: :delete, class: 'button is-link is-pulled-right' %><br>

<% end %>
<hr>

</div>	

app/views/relationships/followers.html.erb
  <%= link_to "Back Home",  notes_path, class: "button is-link", style: "margin-top: 120px; margin-left: 100px;" %>

<div class="followers" style=" margin-left: 300px; margin-right: 300px; margin-top: 50px;">

<% @users.each do |user| %>

   <div class="tags has-addons">  
  <span class="tag is-dark is-light"> <%= user.email %></span> 

</div>


<% notes = user.notes.to_a %>

<% notes.each do |note| %>
<div class="box" >	
   <div class="tags has-addons"> 	
  <span class="tag is-success is-medium"> <%= note.topic_name %></span> 
     <span class="tag is-link  is-medium is-pulled-right"> <%= note.created_at.localtime.strftime("%A, %b %d,  %l:%M %p") %>


      </span>
</div>


  
  	<%= link_to "Delete", note_path(note), method: :delete,  data: {remote: true }, class: "button is-info is-pulled-right" %>  	
     <%= sanitize note.notes %> <br>

     <%= link_to "Add subtopic", note_path(note) %>
   </div>

 <% end %>  

 <% end %>  
  
  </div>

app/views/relationships/index.html.erb
<div class="box" style="margin-left: 200px; width: 400px; margin-top: 150px;">

<% @users.each do |user| %>

<%=  user.email %>   <%= link_to 'Follow', relationships_path(follower_id: user.id), method: :post, class:'button is-link is-pulled-right' %>  <br>
<%= link_to 'Unfollow', relationship_path(user.id), method: :delete, class: 'button is-link is-pulled-right' %><br>

<hr>

<% end %>
</div>	


<div style="margin-left: 250px">

  <%= link_to 'Followers Feed', followers_path, data: {remote: true}, class: 'button is-link' %>

</div>